### ISSUE TITLE
Dockerfileとdocker-compose.ymlの作成

### ISSUE THREAD

**Issue by bugnood** [bugnood/FAL.Project.linne#6]
client/Dockerfile
```
# Dockerfile for React app
FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]

```

server/Dockerfile
```
# Dockerfile for Express server
FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "start"]

```

./Dockerfile
```
# Dockerfile for managing both services (React + Express)
# This Dockerfile is not required for building images, it's just for reference

# Build React app
FROM node:18-alpine AS react-builder
WORKDIR /usr/src/app/client
COPY client/package*.json ./
RUN npm install
COPY client .
RUN npm run build

# Build Express server
FROM node:18-alpine AS express-builder
WORKDIR /usr/src/app/server
COPY server/package*.json ./
RUN npm install
COPY server .
RUN npm run build

# Final image combining React app and Express server
FROM node:18-alpine
WORKDIR /usr/src/app
COPY --from=react-builder /usr/src/app/client/build ./client/build
COPY --from=express-builder /usr/src/app/server ./server

EXPOSE 5000

CMD ["node", "./server/index.js"]

```

./docker-compose.yml
```
version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npx nodemon --legacy-watch index.ts
```
